### ISSUE TITLE
Dotenv/.env loading

### ISSUE THREAD

**Issue by pringithub** [anthonykrivonos/Quantico#1]
First want to say thanks for making this - I was working on something similar and you saved me some time :)

When I try to run the main script, with dotenv installed, I get an error:
`ImportError: cannot import name 'Dotenv' from 'dotenv' (/usr/local/lib/python3.7/site-packages/dotenv/__init__.py)`

I think you meant to have:
`from dotenv import load_dotenv`
instead of 
`from dotenv import Dotenv`

or perhaps there is a mapping you have?

**Comment by anthonykrivonos** [comment]
@pringithub Thanks a bunch! Mind pulling the latest commit from `master` and letting me know if it resolves your issue?

**Comment by pringithub** [comment]
yea it worked
